version: "3.5"

services:
  go_web_server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /server
    volumes:
      - .:/server
    depends_on:
      - db
    ports:
      - "8080:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=m_user
      - DB_PASSWORD=user_password
      - DB_NAME=bookstore
    entrypoint: go run cmd/main.go
    restart: always

  db: # also hostname
    image: postgres:15.1-alpine
    volumes:
      - ./docker_pg_init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      #- POSTGRES_USER=pp_admin
      - POSTGRES_PASSWORD=root
    restart: always

  postgres-client:
    container_name: 'postgres-client'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "db_admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "db_password"
    ports:
      - "16543:80"
    depends_on:
      - db
    